name: Android App Releases
on:
  schedule:
    - cron: '0 0 1 */2 *'
  workflow_dispatch:
    inputs:
      upload_releases:
        description: 'Upload releases'
        required: true
        default: true
        type: boolean
      mark_prerelease:
        description: 'Mark as prerelease'
        required: true
        default: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    uses: mlm-games/ci/.github/workflows/android-release.yml@v1
    with:
      app-name: Forigon
      app-slug: forigon
      application-id: app.forigon
      play-track: ''
    secrets:
      KEYSTORE: ${{ secrets.KEYSTORE }}
      KEYSTORE_PASSPHRASE: ${{ secrets.KEYSTORE_PASSPHRASE }}
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
